name: expat core forking for GitHub Actions

on:
  push:
    branches:
      - no-available-just-rename-in-case-you-want

permissions:
  contents: write
  pull-requests: write

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Obtain source code from fossies.org
        run: |
          wget https://fossies.org/linux/www/expat-2.6.2.tar.xz -O expat-2.6.2.tar.xz

      - name: Install Zstandard for Extraction
        run: sudo apt install -y xz-utils tar

      - name: Extract Source Code into Root Directory
        run: tar --strip-components=1 -xf expat-2.6.2.tar.xz

      - name: Commit Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "expat core forking for GitHub Actions, version 2.6.2"
          git push
